# Generated by Django 2.1.5 on 2019-02-08 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('region', models.CharField(default='', max_length=255)),
                ('geojson', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=255)),
                ('income', models.IntegerField(default=0)),
                ('education', models.CharField(default='', max_length=255)),
                ('numCars', models.IntegerField(default=0)),
                ('yearsResiding', models.IntegerField(default=0)),
                ('ownOrRent', models.CharField(default='', max_length=255)),
                ('numMembers', models.IntegerField(default=0)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_console.Barangay')),
                ('datafile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_console.DataFile')),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='', max_length=255)),
                ('age', models.IntegerField(default=0)),
                ('occupation', models.CharField(default='', max_length=255)),
                ('tripPurpose', models.CharField(default='', max_length=255)),
                ('destAddress', models.CharField(default='', max_length=255)),
                ('tripMode', models.CharField(default='', max_length=255)),
                ('travelTime', models.IntegerField(default=0)),
                ('job', models.CharField(default='', max_length=255)),
                ('income', models.IntegerField(default=0)),
                ('gasOrDiesel', models.CharField(default='', max_length=255)),
                ('fuelCost', models.IntegerField(default=0)),
                ('isFloodProne', models.BooleanField(default=False)),
                ('addTime', models.IntegerField(default=0)),
                ('addCost', models.IntegerField(default=0)),
                ('destBarangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_console.Barangay')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_console.Household')),
            ],
        ),
        migrations.AddField(
            model_name='barangay',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_console.City'),
        ),
    ]
