# Generated by Django 2.1.5 on 2019-03-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='classification',
            field=models.CharField(default='', max_length=255),
        ),
    ]
