# Generated by Django 2.1.5 on 2019-02-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='geojson',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='city',
            name='geojson',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
