# Generated by Django 2.1.5 on 2019-02-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0002_auto_20190209_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.CharField(default='', max_length=255),
        ),
    ]
