# Generated by Django 2.1.5 on 2019-04-25 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0002_amenity_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='OD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_barangay', to='admin_console.Barangay')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_barangay', to='admin_console.Barangay')),
            ],
        ),
    ]
