# Generated by Django 2.1.5 on 2019-02-22 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0003_city_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coefficient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(default='', max_length=255)),
                ('coefficient', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='barangay',
            name='income',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='barangay',
            name='population',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coefficient',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_console.Indicator'),
        ),
    ]
