# Generated by Django 2.1.5 on 2019-03-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0004_auto_20190222_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='barangay',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
