# Generated by Django 2.1.5 on 2019-06-06 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0004_surveyfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='user',
        ),
        migrations.DeleteModel(
            name='DataFile',
        ),
    ]
