# Generated by Django 2.1.5 on 2019-03-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0005_auto_20190308_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='economic',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='barangay',
            name='fairness',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='barangay',
            name='performance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='barangay',
            name='physical',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='barangay',
            name='physiological',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='barangay',
            name='psychological',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='barangay',
            name='spatial',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='barangay',
            name='sustainability',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='barangay',
            name='temporal',
            field=models.FloatField(default=0.0),
        ),
    ]
