# Generated by Django 2.1.5 on 2019-06-06 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0006_auto_20190606_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyfile',
            old_name='collected_by',
            new_name='date_collected',
        ),
    ]
