# Generated by Django 2.1.5 on 2019-06-06 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0007_auto_20190606_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyfile',
            name='file',
            field=models.FileField(max_length=500, null=True, upload_to='surveys'),
        ),
    ]
