# Generated by Django 2.1.5 on 2019-03-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0007_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
