# Generated by Django 2.1.5 on 2019-06-06 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0009_auto_20190606_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='household',
            old_name='extra_details',
            new_name='address_extra',
        ),
        migrations.RenameField(
            model_name='householdmember',
            old_name='destAddress',
            new_name='income_range',
        ),
        migrations.RenameField(
            model_name='householdmember',
            old_name='isFloodProne',
            new_name='is_flood_prone',
        ),
        migrations.RenameField(
            model_name='householdmember',
            old_name='gasOrDiesel',
            new_name='submission_id',
        ),
        migrations.RenameField(
            model_name='householdmember',
            old_name='addCost',
            new_name='travel_time',
        ),
        migrations.RenameField(
            model_name='householdmember',
            old_name='tripMode',
            new_name='trip_mode',
        ),
        migrations.RenameField(
            model_name='householdmember',
            old_name='tripPurpose',
            new_name='trip_purpose',
        ),
        migrations.RemoveField(
            model_name='householdmember',
            name='addTime',
        ),
        migrations.RemoveField(
            model_name='householdmember',
            name='destBarangay',
        ),
        migrations.RemoveField(
            model_name='householdmember',
            name='fuelCost',
        ),
        migrations.RemoveField(
            model_name='householdmember',
            name='income',
        ),
        migrations.RemoveField(
            model_name='householdmember',
            name='travelTime',
        ),
        migrations.AddField(
            model_name='household',
            name='submission_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='dest_address',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='dest_address_extra',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='dest_barangay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_console.Barangay'),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='fare',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='fuel_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='gas_or_diesel',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='new_cost',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='new_time',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='will_cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='household',
            name='barangay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_console.Barangay'),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='job',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
