# Generated by Django 2.1.5 on 2019-03-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0010_auto_20190311_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='osm_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
