# Generated by Django 2.1.5 on 2019-06-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0010_auto_20190606_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyfile',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
