# Generated by Django 2.1.5 on 2019-06-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0011_surveyfile_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='submission_time',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
