# Generated by Django 2.1.5 on 2019-06-08 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0012_household_submission_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdMemberDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(default='', max_length=255, null=True)),
                ('income_range', models.CharField(default='', max_length=255)),
                ('trip_purpose', models.CharField(default='', max_length=255)),
                ('dest_address', models.CharField(default='', max_length=255, null=True)),
                ('dest_address_extra', models.TextField(default='', null=True)),
                ('trip_mode', models.CharField(default='', max_length=255)),
                ('travel_time', models.IntegerField(default=0)),
                ('gas_or_diesel', models.CharField(default='', max_length=255, null=True)),
                ('fuel_cost', models.FloatField(default=0.0)),
                ('fare', models.FloatField(default=0.0)),
                ('is_flood_prone', models.BooleanField(default=False)),
                ('will_cancel', models.BooleanField(default=False)),
                ('new_time', models.FloatField(default=0.0, null=True)),
                ('new_cost', models.FloatField(default=0.0, null=True)),
                ('dest_barangay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_console.Barangay')),
            ],
        ),
        migrations.RemoveField(
            model_name='householdmember',
            name='dest_address',
        ),
        migrations.RemoveField(
            model_name='householdmember',
            name='dest_address_extra',
        ),
        migrations.RemoveField(
            model_name='householdmember',
            name='dest_barangay',
        ),
        migrations.RemoveField(
            model_name='householdmember',
            name='fare',
        ),
        migrations.RemoveField(
            model_name='householdmember',
            name='fuel_cost',
        ),
        migrations.RemoveField(
            model_name='householdmember',
            name='gas_or_diesel',
        ),
        migrations.RemoveField(
            model_name='householdmember',
            name='income_range',
        ),
        migrations.RemoveField(
            model_name='householdmember',
            name='is_flood_prone',
        ),
        migrations.RemoveField(
            model_name='householdmember',
            name='job',
        ),
        migrations.RemoveField(
            model_name='householdmember',
            name='new_cost',
        ),
        migrations.RemoveField(
            model_name='householdmember',
            name='new_time',
        ),
        migrations.RemoveField(
            model_name='householdmember',
            name='travel_time',
        ),
        migrations.RemoveField(
            model_name='householdmember',
            name='trip_mode',
        ),
        migrations.RemoveField(
            model_name='householdmember',
            name='trip_purpose',
        ),
        migrations.RemoveField(
            model_name='householdmember',
            name='will_cancel',
        ),
        migrations.AddField(
            model_name='householdmemberdetails',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_console.HouseholdMember'),
        ),
    ]
