# Generated by Django 2.1.5 on 2019-06-08 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0014_mainhouseholdmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='householdmemberdetails',
            name='dest_barangay',
        ),
        migrations.RemoveField(
            model_name='householdmemberdetails',
            name='household',
        ),
        migrations.DeleteModel(
            name='HouseholdMemberDetails',
        ),
    ]
