# Generated by Django 2.1.5 on 2019-06-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0015_auto_20190608_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyfile',
            name='file',
            field=models.FileField(max_length=500, null=True, upload_to='upload/survey/'),
        ),
    ]
