# Generated by Django 2.1.5 on 2019-08-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0016_auto_20190608_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='area',
            field=models.FloatField(default=0.0),
        ),
    ]
