# Generated by Django 2.1.5 on 2019-09-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0017_barangay_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainhouseholdmember',
            name='travel_distance',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
